#!/bin/bash
set -e

MODE=$1
TIME_STAMP=$2
TOGGLE_OUTLINE=$3

cleanup () {
  # Remove the mod* files from the new app
  DIR_APP_LOCAL=$1

  echo 'Cleaning up the app'
  rm -rf $DIR_APP_LOCAL/mod
  rm $DIR_APP_LOCAL/mod*
}

DIR_MAIN=$PWD

DIR_APP=$DIR_MAIN/$APP_NAME

echo '-------'
echo 'ruby -v'
ruby -v

echo '-------------------'
echo 'cat /etc/os-release'
cat /etc/os-release
echo ''

echo '-----------------'
echo 'bundler --version'
bundler --version
echo ''

echo '----------------'
echo 'gem list bundler'
gem list bundler
echo ''

echo '--------'
echo 'rails -v'
rails -v
echo ''

echo '-----------'
echo 'Time Stamp:'
echo "$TIME_STAMP"
echo ''

echo '-----------'
echo "MODE: $MODE"

####################################
# BEGIN: Set the name of the new app
####################################
APP_NAME='tmp1'
if [ "$MODE" = 'short' ]
then
  APP_NAME="rail0-$TIME_STAMP"
elif [ "$MODE" = 'full' ]
then
  APP_NAME="railn-$TIME_STAMP"
fi
##################################
# END: Set the name of the new app
##################################

##################################
# Set the directory of the new app
##################################
DIR_APP=$PWD/$APP_NAME

# Removing the old Rails app
rm -rf $DIR_APP

echo '--------------------------------'
echo 'BEGIN: installing necessary gems'
echo '--------------------------------'
gem install insert_from_file
gem install line_containing
gem install gemfile_entry
gem install string_in_file
gem install replace_quotes
gem install remove_double_blank
echo '------------------------------'
echo 'END: installing necessary gems'
echo '------------------------------'

#########################################
# BEGIN: initial app creation/acquisition
#########################################
if [ "$MODE" = 'test' ]
then
  echo '-------------------------------------------------------'
  echo 'Downloading the basic Rails app instead of creating one'
else
  # Creating the new Rails app
  echo '--------------------------'
  echo "BEGIN: rails new $APP_NAME"
  echo '--------------------------'
  cd $DIR_MAIN && rails new $APP_NAME
  echo '------------------------'
  echo "END: rails new $APP_NAME"
  echo '------------------------'
fi
#######################################
# END: initial app creation/acquisition
#######################################

#################################################
# Copy mod_app.sh to the new app's root directory
#################################################
cp $DIR_MAIN/mod_app.sh $DIR_APP

########################################################
# Copy the mod directory to the new app's root directory
########################################################
cp -R $DIR_MAIN/mod $DIR_APP

#########################################
# BEGIN: Step 01-01 (except in test mode)
#########################################
if [ "$MODE" != 'test' ]
then
  echo "$TIME_STAMP" > $DIR_APP/config/timestamp.txt
  cd $DIR_APP && bash mod_app.sh '01-01' $TOGGLE_OUTLINE
fi
#######################################
# END: Step 01-01 (except in test mode)
#######################################

if [ "$MODE" = 'short' ]
then
  echo '--------------'
  echo 'bundle install'
  cd $DIR_APP && bundle install

  echo '------------'
  echo 'yarn install'
  cd $DIR_APP && yarn install

  echo '---------------------------'
  echo 'bundle exec rake db:migrate'
  cd $DIR_APP && bundle exec rake db:migrate

  cleanup $DIR_APP

  echo '##############################'
  echo 'The basic app has been created'
  echo "App Name: $APP_NAME"
  
  exit 0
fi
