#!/bin/bash
set -e

MODE=$1
TIME_STAMP=$2
TOGGLE_OUTLINE=$3

DIR_MAIN=$PWD

DIR_APP=$DIR_MAIN/$APP_NAME

echo '-------'
echo 'ruby -v'
ruby -v

echo '-------------------'
echo 'cat /etc/os-release'
cat /etc/os-release
echo ''

echo '-----------------'
echo 'bundler --version'
bundler --version
echo ''

echo '----------------'
echo 'gem list bundler'
gem list bundler
echo ''

echo '--------'
echo 'rails -v'
rails -v
echo ''

echo '-----------'
echo 'Time Stamp:'
echo "$TIME_STAMP"
echo ''

echo '-----------'
echo "MODE: $MODE"

# Set the name of the new app
APP_NAME='tmp1'
if [ "$MODE" = 'short' ]
then
  APP_NAME="rail0-$TIME_STAMP"
elif [ "$MODE" = 'full' ]
then
  APP_NAME="railn-$TIME_STAMP"
fi

# Set the directory of the new app
DIR_APP=$PWD/$APP_NAME

# Removing the old Rails app
rm -rf $DIR_APP

# Skip Step 01-01 in test mode
if [ "$MODE" = 'test' ]
then
  echo '-------------------------------------------------------'
  echo 'Downloading the basic Rails app instead of creating one'
else
  # Creating the new Rails app
  echo '-----------------------------------'
  echo "cd $DIR_MAIN && rails new $APP_NAME"
  cd $DIR_MAIN && rails new $APP_NAME
  wait

  # Executing Step 01-01
fi

# Stop after Step 01-01 in short mode
if [ "$MODE" = 'short' ]
then
  echo '--------------'
  echo 'bundle install'
  cd $DIR_APP && bundle install

  echo '------------'
  echo 'yarn install'
  cd $DIR_APP && yarn install

  echo '---------------------------'
  echo 'bundle exec rake db:migrate'
  cd $DIR_APP && bundle exec rake db:migrate

  echo '##############################'
  echo 'The basic app has been created'
  echo "App Name: $APP_NAME"
  
  exit 0
fi
